name: Build

on:
  [workflow_dispatch, pull_request]

jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive
    
    # - name: Install clang-format 19
    #   uses: KyleMayes/install-llvm-action@v2
    #   with:
    #     version: "19"
    #     cached: true
    
    # - name: Check formatting
    #   working-directory: ${{github.workspace}}
    #   run: |
    #     echo "clang-format version:"
    #     clang-format --version
    #     chmod +x format.sh
    #     ./format.sh
    #     git diff --exit-code
    
    - name: Build Tools
      working-directory: ${{github.workspace}}/build
      env:
        CXX: clang++
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build . -j4
    
    - name: Run tests
      working-directory: ${{github.workspace}}
      run: |
        ./build/tools/run_tests
        ./build/tools/benchmodel ./example_models/wavenet.nam
        ./build/tools/benchmodel ./example_models/lstm.nam
        ./build/tools/render ./example_models/wavenet.nam ./example_audio/input.wav ./example_audio/output.wav
