name: Run Integration Tests

on:
  pull_request:
    branches: [main, integration-tests]

jobs:
  call-integration-tests:
    uses: Atkinson-Advanced-Modeling/NamIntegrationTests/.github/workflows/integration-tests.yml@main
    with:
      source_repo: NeuralAmpModelerCore
      ref: ${{ github.event.pull_request.head.sha }}
